language: python
python:
    - "2.7"
install:
    - pip install -r .travis_requirements.txt
before_install:
    - sudo apt-get update
    - sudo apt-get build-dep python-pygame
    - sudo apt-get install python-pygame
script:
    - make test
virtualenv:
    system_site_packages: true
